### ISSUE TITLE
Crash on Android 14 devices [One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts]

### ISSUE THREAD

**Issue by kunalpowar** [juspay/hyper-sdk-flutter#14]
I am seeing this crash report on Android 14 devices. 

Its related to [this](https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported) change for the newer version.

Fatal Exception: java.lang.SecurityException: com.sample.app: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
       at android.os.Parcel.createException(Parcel.java:3041)
       at android.os.Parcel.readException(Parcel.java:3024)
       at android.os.Parcel.readException(Parcel.java:2966)
       at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
       at in.juspay.hypersdk.core.SmsConsentHandler.lambda$new$0(:10)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

**Comment by kunalpowar** [comment]
Any updates on this? We are seeing quite a few crashes on our app in production because of this.

**Comment by harshgarg18** [comment]
This is fixed in hypersdkflutter version `4.0.6+`

**Comment by neerajpathakcis** [comment]
Facing same issue in react native. version is 0.68.0 and added android:exported true or false to all the receiver but and other solution but none of them worked.Any help would be appreciated

Thanks
